export const SELECTED_HERO = "SELECT_HERO";
export const SELECTED_NEUTRAL = "SELECTED_NEUTRAL";
export const SELECTED_ITEM = "SELECTED_ITEM";
export const SELECTED_BACKPACK_ITEM = "SELECTED_BACKPACK_ITEM";
export const SELECTED_TALENT = "SELECTED_TALENT";
export const UNSELECTED_TALENT = "UNSELECTED_TALENT";
export const NEW_HERO_LEVEL = "NEW_HERO_LEVEL";
export const C = "ITEM_EXTRAS_CHANGED";

export const LANGUAGE_CHANGED = "LANGUAGE_CHANGED";

export const ENEMY_SELECTED = "ENEMY_SELECTED";
export const ENEMY_SELECTED_TALENT = "ENEMY_SELECTED_TALENT";
