export const SELECTED_HERO = "SELECT_HERO";
export const SELECTED_NEUTRAL = "SELECTED_NEUTRAL";
export const SELECTED_ITEM = "SELECTED_ITEM";
export const SELECTED_BACKPACK_ITEM = "SELECTED_BACKPACK_ITEM";
export const SELECTED_TALENT = "SELECTED_TALENT";
export const UNSELECTED_TALENT = "UNSELECTED_TALENT";
export const NEW_HERO_LEVEL = "NEW_HERO_LEVEL";